<a href="https://colab.research.google.com/github/sm-aminul-islam/Python/blob/main/LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn import linear_model


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Gluecose-Level-Age.csv to Gluecose-Level-Age (1).csv


In [ ]:
df=pd.read_csv('Gluecose-Level-Age.csv')

In [ ]:
df

Age  Gluecose-level
0   43              99
1   21              65
2   25              79
3   42              75
4   57              87
5   59              81

In [ ]:
df.shape

(6, 2)

In [ ]:
x=df['Age']
y=df['Gluecose-level']

In [ ]:
x

0    43
1    21
2    25
3    42
4    57
5    59
Name: Age, dtype: int64

In [ ]:
y

0    99
1    65
2    79
3    75
4    87
5    81
Name: Gluecose-level, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30,random_state=1)

In [ ]:
xtrain

4    57
0    43
3    42
5    59
Name: Age, dtype: int64

In [ ]:
ytrain

4    87
0    99
3    75
5    81
Name: Gluecose-level, dtype: int64

In [ ]:
xtest

2    25
1    21
Name: Age, dtype: int64

In [ ]:
ytest

2    79
1    65
Name: Gluecose-level, dtype: int64

In [50]:
from sklearn.linear_model import LinearRegression

In [51]:
reg = LinearRegression()

In [69]:
xtrain.shape

(4,)

In [71]:
ytrain.shape

(4,)

In [72]:
import numpy as np

In [73]:
xtrain = np.asarray(xtrain).reshape(-1,1)

In [74]:
xtrain.shape

(4, 1)

In [79]:
xtest.shape

(2,)

In [80]:
xtest=np.asarray(xtest).reshape(-1,1)

In [81]:
xtest.shape

(2, 1)

In [75]:
reg.fit(xtrain, ytrain)

LinearRegression()

In [82]:
reg.predict(xtest)

array([89.71266735, 90.3800206 ])

In [83]:
ytest

2    79
1    65
Name: Gluecose-level, dtype: int64

In [85]:
reg.predict([[55]])

array([84.70751802])

In [ ]:
#manual calculation

In [87]:
reg.coef_  # m

array([-0.16683831])

In [88]:
reg.intercept_

93.88362512873326

In [89]:
#y=mx+c
y=reg.coef_ * 59+reg.intercept_

In [90]:
y

array([84.04016478])